### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by fachos** [spiritLHLS/honeygain-one-click-command-installation#2]
Hi... i registered honeygain using your referral and successfully install the script but at the end after docker pull the image got this warning 

**WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested**

is it ok? run on armbian aarch64/arm64v8...

last question...  can i install others like iproyal, traffmonetizer etc all together? 

thank you

**Comment by fachos** [comment]
i found the solution install binfmt & add line: 

1- docker run --privileged --rm tonistiigi/binfmt --install all 
2- edit line in hg.sh

docker run -d --name "$NAME" --restart=always honeygain/honeygain -tou-accept -email "$EMAIL" -pass "$PASSWORD" -device honeygainnode

to
 
docker run -d --name "$NAME" --restart=always **--platform linux/amd64** honeygain/honeygain -tou-accept -email "$EMAIL" -pass "$PASSWORD" -device honeygainnode

**Comment by spiritLHLS** [comment]
https://hub.docker.com/r/honeygain/honeygain/tags

I checked the official image and it seems that the deployment of machines with arm64 architecture is not allowed at the moment, so I'm sorry this modification doesn't work (the official docker is not cross-compiled, only amd64 is adapted)

As for whether it is possible to run multiple projects at the same time, the result is yes, I have written shell scripts corresponding to the projects you mentioned:

https://github.com/spiritLHLS/Hang-up-items#%E6%8C%82%E6%9C%BA%E9%A1%B9%E7%9B%AE%E5%90%88%E9%9B%86
